function subscriptionEntries(rows){
  return rows.flatMap(row=>{
    const details=Array.isArray(row.soldSubscriptions)?row.soldSubscriptions:[];
    const count=Math.max(0,Math.trunc(Number(row.soldSubscriptionsTotal)||0));
    return Array.from({length:count},(_,i)=>({seller:row.seller||'Non specificato',type:String(details[i]?.customerType||'').trim()||'Non specificato',source:String(details[i]?.customerSource||'').trim()||'Non specificato'}));
  });
}
function filterSubscriptions(entries,filters){return entries.filter(e=>['seller','type','source'].every(k=>filters[k]==='all'||e[k]===filters[k]));}
if(typeof module!=='undefined')module.exports={subscriptionEntries,filterSubscriptions};
if(typeof document!=='undefined')(async()=>{
  const user=await SalesAuth.requireAdmin();if(!user)return;
  const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),now=new Date(),iso=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
  $('from').value=params.get('from')||iso(new Date(now.getFullYear(),now.getMonth(),1));$('to').value=params.get('to')||iso(now);
  if(['all','Futura Evo','Futura Fit'].includes(params.get('center')))$('center').value=params.get('center');
  let entries=[],initialSeller=params.get('seller')||'all';
  function options(id,key,label){const selected=id==='seller'&&initialSeller!=='all'?initialSeller:$(id).value;$(id).replaceChildren(new Option(label,'all'));[...new Set(entries.map(e=>e[key]))].sort((a,b)=>a.localeCompare(b,'it')).forEach(v=>$(id).add(new Option(v,v)));$(id).value=[...$(id).options].some(o=>o.value===selected)?selected:'all';}
  function table(title,data,keys){const wrap=document.createElement('div');wrap.className='table-scroll';const t=document.createElement('table'),cap=document.createElement('caption');cap.textContent=title;t.append(cap);const head=t.createTHead().insertRow();[...keys.map(k=>k==='type'?'Tipo cliente':'Fonte cliente'),'Abbonamenti'].forEach(label=>{const th=document.createElement('th');th.textContent=label;head.append(th)});const counts=new Map();data.forEach(e=>{const k=JSON.stringify(keys.map(key=>e[key]));counts.set(k,(counts.get(k)||0)+1)});const body=t.createTBody();[...counts].sort((a,b)=>b[1]-a[1]).forEach(([key,count])=>{const row=body.insertRow();[...JSON.parse(key),count].forEach(value=>{row.insertCell().textContent=value})});wrap.append(t);return wrap;}
  function render(){const filtered=filterSubscriptions(entries,{seller:$('seller').value,type:$('type').value,source:$('source').value});$('results').replaceChildren();$('status').textContent=`${filtered.length} abbonamenti corrispondenti ai filtri.`;const sellers=[...new Set(filtered.map(e=>e.seller))].sort((a,b)=>a.localeCompare(b,'it'));sellers.forEach(seller=>{const data=filtered.filter(e=>e.seller===seller),card=document.createElement('article');card.className='chart-card';const h=document.createElement('h2');h.textContent=`${seller} · ${data.length} abbonamenti`;card.append(h,table('Per tipo cliente',data,['type']),table('Per fonte cliente',data,['source']),table('Tipo cliente e fonte',data,['type','source']));$('results').append(card)});if(!filtered.length)$('status').textContent='Nessun abbonamento trovato con questi filtri.';}
  async function load(){if(!$('filters').reportValidity())return;if($('from').value>$('to').value){$('status').textContent='La data iniziale deve precedere quella finale.';return;}$('apply').disabled=true;$('status').textContent='Caricamento…';$('results').replaceChildren();try{const q=new URLSearchParams({action:'report',from:$('from').value,to:$('to').value,center:$('center').value,seller:'all'});const response=await fetch(`${window.SALES_APP_CONFIG.GOOGLE_SCRIPT_URL}?${q}`),data=await response.json();if(!data.ok)throw new Error(data.error||'Errore caricamento');if(data.user?.role!=='admin')throw new Error('Accesso riservato admin');entries=subscriptionEntries(data.rows||[]);options('seller','seller','Tutti gli operatori');initialSeller='all';options('type','type','Tutti i tipi');options('source','source','Tutte le fonti');render()}catch(e){entries=[];$('status').textContent=`Impossibile caricare: ${e.message}`}finally{$('apply').disabled=false}}
  $('filters').addEventListener('submit',e=>{e.preventDefault();load()});['seller','type','source'].forEach(id=>$(id).addEventListener('change',render));await load();
})();
