const endpoint=window.SALES_APP_CONFIG?.GOOGLE_SCRIPT_URL?.trim();
const sellers=['Donatella','Elena','Erika','Francesco','Ramses'];
const els={dateFrom:document.getElementById('dateFrom'),dateTo:document.getElementById('dateTo'),center:document.getElementById('centerFilter'),seller:document.getElementById('performanceSeller'),apply:document.getElementById('applyFilters'),toggles:[...document.querySelectorAll('.performance-toggle')],chart:document.getElementById('performanceIndexChart'),breakdown:document.getElementById('performanceBreakdown'),message:document.getElementById('reportMessage')};
let currentRows=[];
const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1),localIso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);els.dateFrom.value=localIso(first);els.dateTo.value=localIso(now);
const n=v=>Number(v)||0;
function effectiveWorkedHours(row){const direct=n(row.workedHours);if(direct>0)return direct;if(!row.entryTime||!row.exitTime)return 0;const parse=t=>{const m=String(t).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null},start=parse(row.entryTime),end=parse(row.exitTime);if(start===null||end===null)return 0;let minutes=end-start;if(minutes<0)minutes+=1440;return minutes/60}
function aggregate(rows){const a={workedHours:0,messagesSent:0,callsMade:0,quotesTotal:0,soldSubscriptionsTotal:0,passesVouchersDelivered:0,passesVouchersActivated:0};for(const r of rows){a.workedHours+=effectiveWorkedHours(r);a.messagesSent+=n(r.messagesSent);a.callsMade+=n(r.callsMade);a.quotesTotal+=n(r.quotesTotal);a.soldSubscriptionsTotal+=n(r.soldSubscriptionsTotal);a.passesVouchersDelivered+=n(r.passesVouchersDelivered);a.passesVouchersActivated+=n(r.passesVouchersActivated)}return a}
function metricValue(a,key){if(key==='quotes')return a.quotesTotal;return n(a[key])}
function setupCanvas(canvas){const dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(),w=Math.max(rect.width,500),h=Math.max(rect.height,250);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h}}
function drawEmpty(msg){const{ctx,w,h}=setupCanvas(els.chart);ctx.clearRect(0,0,w,h);ctx.fillStyle='#9ca3af';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText(msg,w/2,h/2)}
function drawBars(items){if(!items.length||items.every(i=>!i.score))return drawEmpty('Nessun indice disponibile');const{ctx,w,h}=setupCanvas(els.chart);ctx.clearRect(0,0,w,h);const pad={l:48,r:16,t:22,b:55},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=100;ctx.strokeStyle='#e5e7eb';for(let i=0;i<5;i++){const y=pad.t+ch*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#9ca3af';ctx.font='10px Arial';ctx.textAlign='right';ctx.fillText(`${Math.round(100-i*25)}%`,pad.l-6,y+3)}const slot=cw/items.length,bw=Math.min(90,slot*.55);items.forEach((it,i)=>{const bh=ch*Math.min(it.score,max)/max,x=pad.l+i*slot+(slot-bw)/2,y=pad.t+ch-bh;ctx.fillStyle=['#6d28d9','#0891b2','#059669','#ea580c','#dc2626'][i%5];ctx.fillRect(x,y,bw,bh);ctx.fillStyle='#111827';ctx.font='700 12px Arial';ctx.textAlign='center';ctx.fillText(`${it.score.toFixed(1)}%`,x+bw/2,Math.max(14,y-6));ctx.fillStyle='#6b7280';ctx.font='11px Arial';ctx.fillText(it.seller,x+bw/2,pad.t+ch+20)});ctx.textAlign='left'}
function render(){const selected=els.toggles.filter(t=>t.checked).map(t=>t.value);if(!currentRows.length){drawEmpty('Nessun dato nel periodo selezionato');els.breakdown.innerHTML='<div class="performance-notice">Nessun dato disponibile con i filtri correnti.</div>';return}if(!selected.length){drawEmpty('Seleziona almeno una azione');els.breakdown.innerHTML='<div class="performance-notice">Seleziona almeno una voce per calcolare la performance.</div>';return}const allAgg=sellers.map(s=>({seller:s,a:aggregate(currentRows.filter(r=>r.seller===s))})),maxPerMetric={};for(const key of selected)maxPerMetric[key]=Math.max(...allAgg.map(x=>x.a.workedHours>0?metricValue(x.a,key)/x.a.workedHours:0),0);const source=els.seller.value==='all'?allAgg:allAgg.filter(x=>x.seller===els.seller.value);const scores=source.map(x=>{const parts=selected.map(key=>{const rate=x.a.workedHours>0?metricValue(x.a,key)/x.a.workedHours:0,max=maxPerMetric[key];return max>0?rate/max*100:0});return{seller:x.seller,hours:x.a.workedHours,actions:selected.reduce((sum,key)=>sum+metricValue(x.a,key),0),score:parts.length?parts.reduce((s,v)=>s+v,0)/parts.length:0}});if(!allAgg.some(x=>x.a.workedHours>0)){drawEmpty('Ore lavorate mancanti');els.breakdown.innerHTML='<div class="performance-notice">Per calcolare l’indice servono Ore lavorate oppure Ora ingresso/Ora uscita.</div>';return}drawBars(scores);els.breakdown.innerHTML=scores.map(x=>`<div class="performance-score"><span>${x.seller}</span><strong>${x.score.toFixed(1)}%</strong><small>${x.hours.toFixed(1)} h · ${x.actions} azioni selezionate</small></div>`).join('')}
async function load(){if(!endpoint){els.message.textContent='Collegamento Google Sheet non configurato.';return}els.apply.disabled=true;els.apply.textContent='Caricamento…';els.message.textContent='';try{const q=new URLSearchParams({action:'report',from:els.dateFrom.value,to:els.dateTo.value,seller:'all',center:els.center.value});const res=await fetch(`${endpoint}?${q}`),data=await res.json();if(!data.ok)throw new Error(data.error||'Errore lettura dati');currentRows=data.rows||[];render();els.message.textContent=`Aggiornato: ${currentRows.length} record.`}catch(e){currentRows=[];render();els.message.textContent=`Impossibile caricare l’indice: ${e.message}`}finally{els.apply.disabled=false;els.apply.textContent='Aggiorna indice'}}
els.apply.addEventListener('click',load);els.toggles.forEach(t=>t.addEventListener('change',render));els.seller.addEventListener('change',render);window.addEventListener('resize',()=>requestAnimationFrame(render));load();