const endpoint=window.SALES_APP_CONFIG?.GOOGLE_SCRIPT_URL?.trim();
const els={dateFrom:document.getElementById('dateFrom'),dateTo:document.getElementById('dateTo'),seller:document.getElementById('sellerFilter'),center:document.getElementById('centerFilter'),apply:document.getElementById('applyFilters'),toggles:[...document.querySelectorAll('.metric-toggle')],kpis:document.getElementById('kpiGrid'),actions:document.getElementById('actionsChart'),conversion:document.getElementById('conversionChart'),sales:document.getElementById('salesChart'),sellerChart:document.getElementById('sellerChart'),hours:document.getElementById('hoursChart'),messages:document.getElementById('messagesChart'),subscriptions:document.getElementById('subscriptionsChart'),sources:document.getElementById('sourcesChart'),birthdayDetails:document.getElementById('birthdayDetails'),subscriptionDetails:document.getElementById('subscriptionDetails'),period:document.getElementById('periodLabel'),sellerLabel:document.getElementById('sellerLabel'),centerLabel:document.getElementById('centerLabel'),rows:document.getElementById('rowsLabel'),message:document.getElementById('reportMessage'),export:document.getElementById('exportJpg')};
let currentRows=[];
const sellers=['Donatella','Elena','Erika','Francesco','Ramses'];
const now=new Date(),first=new Date(now.getFullYear(),now.getMonth(),1),localIso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);els.dateFrom.value=localIso(first);els.dateTo.value=localIso(now);
const n=v=>Number(v)||0,euro=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n(v));
function aggregate(rows){const a={workedHours:0,messagesSent:0,birthdayMessagesSent:0,callsMade:0,callsAnswered:0,appointmentsFromCalls:0,quotesFromCalls:0,subscriptionsFromCalls:0,toursDone:0,quotesFromTours:0,subscriptionsFromTours:0,organicQuotes:0,subscriptionsFromOrganicQuotes:0,organicRenewals:0,trialsActivated:0,passesVouchersDelivered:0,passesVouchersActivated:0,revenue:0,futuraAmount:0,totalCollected:0,collectedPos:0,collectedCash:0,collectedBank:0,collectedFinance:0,soldSubscriptionsTotal:0};for(const r of rows)for(const k in a)a[k]+=n(r[k]);return a}
function conversion(part,total){return total?part/total*100:0}
function visible(){return new Set(els.toggles.filter(t=>t.checked).map(t=>t.value))}
function renderKpis(rows){const a=aggregate(rows),v=visible(),defs=[];if(v.has('operator'))defs.push(['Ore lavorate',a.workedHours.toFixed(2),'ore totali']);if(v.has('messages'))defs.push(['Messaggi',a.messagesSent,'inviati'],['Mess. compleanno',a.birthdayMessagesSent,'inviati']);if(v.has('calls'))defs.push(['Telefonate',a.callsMade,'totali'],['Appuntamenti',a.appointmentsFromCalls,`${conversion(a.appointmentsFromCalls,a.callsAnswered).toFixed(1)}% su risposte`]);if(v.has('tours'))defs.push(['Tour',a.toursDone,'effettuati'],['Abb. da tour',a.subscriptionsFromTours,`${conversion(a.subscriptionsFromTours,a.quotesFromTours).toFixed(1)}% sui preventivi`]);if(v.has('organic'))defs.push(['Rinnovi',a.organicRenewals,'organici']);if(v.has('other'))defs.push(['Prove',a.trialsActivated,'attivate'],['Pass/Voucher',a.passesVouchersActivated,'attivati']);if(v.has('sales'))defs.push(['Fatturato',euro(a.revenue),'totale'],['Incassato Futura',euro(a.futuraAmount),'totale']);if(v.has('payments'))defs.push(['Totale incassato',euro(a.totalCollected),'registrato']);if(v.has('subscriptions'))defs.push(['Abbonamenti venduti',a.soldSubscriptionsTotal,'totali']);els.kpis.innerHTML=defs.map(([l,val,s])=>`<div class="kpi"><span>${l}</span><strong>${val}</strong><small>${s}</small></div>`).join('')}
function setupCanvas(canvas){const dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=Math.max(500,Math.round(rect.width*dpr));canvas.height=Math.max(250,Math.round(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height}}
function drawEmpty(canvas,msg='Nessun dato'){const{ctx,w,h}=setupCanvas(canvas);ctx.clearRect(0,0,w,h);ctx.fillStyle='#9ca3af';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText(msg,w/2,h/2)}
function barChart(canvas,items,formatter=v=>String(Math.round(v))){const clean=items.filter(i=>i[1]!=null);if(!clean.length||clean.every(i=>!n(i[1])))return drawEmpty(canvas);const{ctx,w,h}=setupCanvas(canvas);ctx.clearRect(0,0,w,h);const pad={l:48,r:16,t:16,b:50},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(...clean.map(i=>n(i[1])),1);ctx.strokeStyle='#e5e7eb';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad.t+ch*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}const slot=cw/clean.length,bw=Math.min(54,slot*.56);clean.forEach((it,i)=>{const val=n(it[1]),bh=ch*val/max,x=pad.l+i*slot+(slot-bw)/2,y=pad.t+ch-bh;ctx.fillStyle=['#6d28d9','#0891b2','#059669','#ea580c','#dc2626'][i%5];ctx.fillRect(x,y,bw,bh);ctx.fillStyle='#111827';ctx.font='700 11px Arial';ctx.textAlign='center';ctx.fillText(formatter(val),x+bw/2,Math.max(12,y-5));ctx.fillStyle='#6b7280';ctx.font='10px Arial';wrapLabel(ctx,it[0],x+bw/2,pad.t+ch+16,slot-6)});ctx.textAlign='left'}
function wrapLabel(ctx,text,x,y,maxWidth){const words=String(text).split(' ');let line='',lineNo=0;ctx.textAlign='center';for(const word of words){const t=line?line+' '+word:word;if(ctx.measureText(t).width>maxWidth&&line){ctx.fillText(line,x,y+lineNo*11);line=word;lineNo++}else line=t}if(line)ctx.fillText(line,x,y+lineNo*11)}
function countSources(rows){const map={};for(const r of rows)for(const item of (Array.isArray(r.soldSubscriptions)?r.soldSubscriptions:[])){const key=(item.customerSource||'Non indicata').trim()||'Non indicata';map[key]=(map[key]||0)+1}return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8)}
function renderDetails(rows){const v=visible();const birthday=[];for(const r of rows){(Array.isArray(r.birthdayOutcomes)?r.birthdayOutcomes:[]).forEach((outcome,i)=>birthday.push({date:r.date,seller:r.seller,n:i+1,outcome:outcome||'—'}))}els.birthdayDetails.innerHTML=v.has('messages')?(birthday.length?birthday.map(x=>`<div class="detail-row"><span>${formatDate(x.date)} · ${x.seller} · Mes. ${x.n}</span><strong>${escapeHtml(x.outcome)}</strong></div>`).join(''):'<p class="empty-detail">Nessun esito nel periodo.</p>'):'';document.getElementById('birthdayDetailCard').hidden=!v.has('messages');const subs=[];for(const r of rows){(Array.isArray(r.soldSubscriptions)?r.soldSubscriptions:[]).forEach((s,i)=>subs.push({date:r.date,seller:r.seller,n:i+1,...s}))}els.subscriptionDetails.innerHTML=v.has('subscriptions')?(subs.length?subs.map(x=>`<div class="detail-row"><span>${formatDate(x.date)} · ${x.seller}</span><strong>${escapeHtml(x.subscriptionType||'—')} · ${escapeHtml(x.customerType||'—')} · ${escapeHtml(x.customerSource||'—')}</strong></div>`).join(''):'<p class="empty-detail">Nessun abbonamento dettagliato nel periodo.</p>'):'';document.getElementById('subscriptionsDetailCard').hidden=!v.has('subscriptions')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderCharts(rows){const a=aggregate(rows),v=visible();document.querySelectorAll('[data-chart-group="operator"]').forEach(x=>x.hidden=!v.has('operator'));document.querySelectorAll('[data-chart-group="messages"]').forEach(x=>x.hidden=!v.has('messages'));document.querySelectorAll('[data-chart-group="subscriptions"]').forEach(x=>x.hidden=!v.has('subscriptions'));
if(v.has('operator'))barChart(els.hours,sellers.map(s=>[s,rows.filter(r=>r.seller===s).reduce((sum,r)=>sum+n(r.workedHours),0)]),x=>x.toFixed(1)+'h');
if(v.has('messages'))barChart(els.messages,[['Messaggi',a.messagesSent],['Compleanno',a.birthdayMessagesSent]]);
const actionItems=[];if(v.has('calls'))actionItems.push(['Telefonate',a.callsMade],['Appuntamenti',a.appointmentsFromCalls]);if(v.has('tours'))actionItems.push(['Tour',a.toursDone]);if(v.has('organic'))actionItems.push(['Preventivi organici',a.organicQuotes],['Rinnovi',a.organicRenewals]);if(v.has('other'))actionItems.push(['Prove',a.trialsActivated],['Pass attivati',a.passesVouchersActivated]);barChart(els.actions,actionItems);
const conv=[];if(v.has('calls'))conv.push(['Risposta tel.',conversion(a.callsAnswered,a.callsMade)],['Abb. da tel.',conversion(a.subscriptionsFromCalls,a.quotesFromCalls)]);if(v.has('tours'))conv.push(['Abb. da tour',conversion(a.subscriptionsFromTours,a.quotesFromTours)]);if(v.has('organic'))conv.push(['Abb. organici',conversion(a.subscriptionsFromOrganicQuotes,a.organicQuotes)]);barChart(els.conversion,conv,x=>x.toFixed(1)+'%');
const sales=[];if(v.has('sales'))sales.push(['Fatturato',a.revenue],['Inc. Futura',a.futuraAmount]);if(v.has('payments'))sales.push(['Incassato',a.totalCollected],['POS',a.collectedPos],['Contanti',a.collectedCash],['Bonifico',a.collectedBank],['Finanziamento',a.collectedFinance]);barChart(els.sales,sales,euro);
barChart(els.sellerChart,sellers.map(s=>[s,rows.filter(r=>r.seller===s).reduce((sum,r)=>sum+n(r.revenue),0)]),euro);
if(v.has('subscriptions')){barChart(els.subscriptions,sellers.map(s=>[s,rows.filter(r=>r.seller===s).reduce((sum,r)=>sum+n(r.soldSubscriptionsTotal),0)]));barChart(els.sources,countSources(rows))}}
function render(rows){els.period.textContent=`${formatDate(els.dateFrom.value)} → ${formatDate(els.dateTo.value)}`;els.sellerLabel.textContent=els.seller.value==='all'?'Tutti':els.seller.value;els.centerLabel.textContent=els.center.value==='all'?'Tutti':els.center.value;els.rows.textContent=rows.length;renderKpis(rows);renderDetails(rows);requestAnimationFrame(()=>renderCharts(rows))}
function formatDate(iso){if(!iso)return'—';const[y,m,d]=iso.split('-');return`${d}/${m}/${y}`}
async function load(){if(!endpoint){els.message.textContent='Collegamento Google Sheet non configurato.';return}els.apply.disabled=true;els.apply.textContent='Caricamento…';els.message.textContent='';try{const q=new URLSearchParams({action:'report',from:els.dateFrom.value,to:els.dateTo.value,seller:els.seller.value,center:els.center.value});const res=await fetch(`${endpoint}?${q}`);const data=await res.json();if(!data.ok)throw new Error(data.error||'Errore lettura dati');currentRows=data.rows||[];render(currentRows);els.message.textContent=`Aggiornato: ${currentRows.length} record.`}catch(e){els.message.textContent=`Impossibile caricare il report: ${e.message}`;currentRows=[];render([])}finally{els.apply.disabled=false;els.apply.textContent='Aggiorna report'}}
els.apply.addEventListener('click',load);els.toggles.forEach(t=>t.addEventListener('change',()=>render(currentRows)));
function drawReportJpg(){const a=aggregate(currentRows),canvas=document.createElement('canvas'),w=1600,h=1200,ctx=canvas.getContext('2d');canvas.width=w;canvas.height=h;ctx.fillStyle='#eef1f4';ctx.fillRect(0,0,w,h);ctx.fillStyle='#111827';ctx.fillRect(45,45,w-90,145);ctx.fillStyle='#fff';ctx.font='700 42px Arial';ctx.fillText('Report performance commerciale',80,105);ctx.fillStyle='#cbd5e1';ctx.font='23px Arial';ctx.fillText(`Periodo ${formatDate(els.dateFrom.value)} - ${formatDate(els.dateTo.value)} · Venditore: ${els.sellerLabel.textContent} · Centro: ${els.centerLabel.textContent}`,80,150);const cards=[['Ore lavorate',a.workedHours.toFixed(2)+' h'],['Messaggi',a.messagesSent],['Mess. compleanno',a.birthdayMessagesSent],['Abbonamenti venduti',a.soldSubscriptionsTotal],['Fatturato',euro(a.revenue)],['Incassato',euro(a.totalCollected)],['Telefonate',a.callsMade],['Appuntamenti',a.appointmentsFromCalls],['Tour',a.toursDone],['Rinnovi',a.organicRenewals],['Prove',a.trialsActivated],['Pass attivati',a.passesVouchersActivated]];const cols=4,cw=(w-120)/cols,ch=108;cards.forEach((c,i)=>{const x=45+(i%cols)*(cw+10),y=225+Math.floor(i/cols)*(ch+12);ctx.fillStyle='#fff';ctx.fillRect(x,y,cw,ch);ctx.fillStyle='#6b7280';ctx.font='18px Arial';ctx.fillText(c[0],x+18,y+30);ctx.fillStyle='#111827';ctx.font='700 30px Arial';ctx.fillText(String(c[1]),x+18,y+72)});const sellerVals=sellers.map(s=>[s,currentRows.filter(r=>r.seller===s).reduce((sum,r)=>sum+n(r.revenue),0)]);ctx.fillStyle='#111827';ctx.font='700 27px Arial';ctx.fillText('Fatturato per venditore',55,610);const max=Math.max(...sellerVals.map(x=>x[1]),1);sellerVals.forEach((it,i)=>{const y=650+i*68,barW=900*it[1]/max;ctx.fillStyle='#374151';ctx.font='20px Arial';ctx.fillText(it[0],55,y+24);ctx.fillStyle='#6d28d9';ctx.fillRect(190,y,barW,32);ctx.fillStyle='#111827';ctx.font='700 20px Arial';ctx.fillText(euro(it[1]),200+barW,y+23)});ctx.fillStyle='#6b7280';ctx.font='17px Arial';ctx.fillText(`Report esportato il ${new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}`,55,h-38);return canvas}
els.export.addEventListener('click',()=>{try{const canvas=drawReportJpg();canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`report-vendite-${els.dateFrom.value}-${els.dateTo.value}.jpg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/jpeg',.94)}catch(e){els.message.textContent=`Esportazione non riuscita: ${e.message}`}});
load();